### ISSUE TITLE
Create DDL for 'NOTE_NLP_MODIFIER' extension table.

### ISSUE THREAD

**Issue by mgurley** [OHDSI/NLPTools#13]
Use OMOP CDM DDL machinery in new branch.

**Comment by kzollove** [comment]
You can now get the DDL with NOTE_NLP updates and the new NOTE_NLP_MODIFIER at the "NLP_Proposal_2023_extension" branch of my CDM fork: https://github.com/kzollove/CommonDataModel/tree/NLP_Proposal_2023_extension
